apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
  annotations:
    kubernetes.io/dockerconfigjson: "true"
type: kubernetes.io/basic-auth
data:
  username: admin
  password: c2VjcmV0cy55YW1sCg