apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
  annotations:
    kubernetes.io/dockerconfigjson: "true"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxNzIuMTcuMC4xOjgwODUiOnsidXNlcm5hbWUiOiJuZXh1cyIsInBhc3N3b3JkIjoibmV4dXMiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20ifX19
